apiVersion: apps/v1
kind: Deployment
metadata:
  name: kata-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kata-operator
  template:
    metadata:
      labels:
        name: kata-operator
    spec:
      serviceAccountName: kata-operator
      containers:
        - name: kata-operator
          # Replace this with the built image name
          image: docker.io/pharshal/kata-operator:v0.0.4 
          command:
          - kata-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kata-operator"
