kind: ConfigMap
apiVersion: v1
metadata:
  name: payload-config
  namespace: kata-operator-system
data:
  # change to your custom payload repository:tag value
  daemon.payload: quay.io/user/repository:test
