apiVersion: batch/v1
kind: Job
metadata:
  name: osc-podvm-image-deletion
  namespace: openshift-sandboxed-containers-operator
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: osc-podvm-image-deletion
    spec:
      containers:
        - name: delete
          # This image contains the following
          # podvm binaries under /payload/podvm-binaries.tar.gz
          # azure-podvm-image-handler.sh script under /scripts/azure-podvm-image-handler.sh
          # aws-podvm-image-handler.sh script under /scripts/aws-podvm-image-handler.sh
          # sources for cloud-api-adaptor under /src/cloud-api-adaptor
          # Binaries like kubectl, packer and yq under /usr/local/bin
          image: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9:1.7.0
          securityContext:
            runAsUser: 0 # needed for container mode dnf access
          env:
            - name: AMI_ID
              value: "" # Set this to the aws ami id to delete
            - name: IMAGE_ID
              value: "" # Set this to the azure image id to delete
            - name: LIBVIRT_IMAGE_ID
              value: "" # Set this to the libvirt image id to delete
          envFrom:
            - secretRef:
                name: peer-pods-secret
            - configMapRef:
                name: peer-pods-cm
                optional: true
            - configMapRef:
                name: azure-podvm-image-cm
                optional: true
            - configMapRef:
                name: aws-podvm-image-cm
                optional: true
            - configMapRef:
                name: libvirt-podvm-image-cm
                optional: true
          command: ["/podvm-builder.sh", "delete", "-f"]
          volumeMounts:
            - name: ssh-key-secret
              mountPath: "/root/.ssh/"
              readOnly: true
              optional: true
      volumes:
        - name: ssh-key-secret
          secret:
            secretName: ssh-key-secret
            items:
            - key: id_rsa
              path: "id_rsa"
            defaultMode: 0400

      restartPolicy: Never
